# Generated by Django 3.0.2 on 2020-01-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommo',
            name='img',
            field=models.ImageField(default='', upload_to='oss/media/images'),
        ),
    ]
