# Generated by Django 3.0.2 on 2020-01-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200120_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommo',
            name='img',
            field=models.ImageField(default='', upload_to='companies/images'),
        ),
    ]
