# Generated by Django 3.0.2 on 2020-01-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='img',
            field=models.ImageField(default='', upload_to='companies/images'),
        ),
    ]
