# Generated by Django 3.0.2 on 2020-01-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10)),
                ('category', models.CharField(default='small', max_length=20)),
                ('capacity', models.IntegerField(default=4)),
                ('ratepm', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('available', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='accommo',
            name='latitude',
            field=models.FloatField(default=27.71),
        ),
        migrations.AddField(
            model_name='accommo',
            name='longitude',
            field=models.FloatField(default=85.32),
        ),
    ]
