# Generated by Django 3.0.2 on 2020-01-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='guidess/')),
                ('name', models.CharField(max_length=20)),
                ('rating', models.ImageField(default='', upload_to='guidess/rating')),
                ('lan', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
            ],
        ),
    ]
