# Generated by Django 3.0.2 on 2020-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='category',
            field=models.CharField(default='Kathmandu', max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='rating',
            field=models.CharField(max_length=20),
        ),
    ]
